### ISSUE TITLE
Laravel 9 ?

### ISSUE THREAD

**Issue by didiergm** [ahmadfaizk/laravel-inertiajs-vuetify-starterkit#5]
Hello

This is exactly what I was looking for, thanks a bunch

I was just wondering how difficult it would be to upgrade to Laravel 9 as I am starting a new project

**Comment by ahmadfaizk** [comment]
Hello @didiergm , sorry for waiting time, i has update the project with laravel 10, and now use vite and vue version 3, thanks.
