### ISSUE TITLE
search people

### ISSUE THREAD

**Issue by pram212** [ahmadfaizk/laravel-inertiajs-vuetify-starterkit#8]
ERROR SQL syntax at PeopleController line 52. to solving this bugs is change "ILIKE" word in the query builder to "LIKE" at line 19

**Comment by ahmadfaizk** [comment]
ILIKE is not a bug in [postgresql](https://www.geeksforgeeks.org/postgresql-ilike-operator/), but thank you for your open issue, i will update it to LIKE and use str lower to handle case-censitive

**Comment by ahmadfaizk** [comment]
I have fix this issue with this [PR](https://github.com/ahmadfaizk/laravel-inertiajs-vuetify-starterkit/pull/9), i change to use LIKE instead to use ILIKE, to generally used database type, thanks
